extends Node
var posicion = Vector2(-18,37)
var vida = 3
var maxvida = 3
var empezar = false
var ciencia = false
var arte = false
var historia = false
var politica = false
var ruleteado = false;
var dialog = false
var caida = false
var disparo = false
var disparo2 = false
var disparo3 = false
var disparo4 = false
var pescar = false
var sword =false;
var empirista = false
var nacionalista = false
var obtenciongema = false
var espadahabilitada = false
var attacking = false
